server:
  port: 8099
spring:
  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456
    #时区和时间格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true